import express from "express";
import authRoutes from "./auth.routes.js";
import studentRoutes from "./student.routes.js";
import chatRoutes from "./chat.routes.js";
import teacherRoutes from "./teacher.routes.js";
import quizRoutes from "./quiz.routes.js";
import subjectRoutes from "./subject.routes.js";
import roadmapRoutes from "./roadmap.routes.js";
import escapeRoutes from "./escape.routes.js";
import dungeonRoutes from "./dungeon.routes.js";
import leaderboardRoutes from "./leaderboard.routes.js";

const router = express.Router();
router.use("/auth", authRoutes);
router.use("/students", studentRoutes);
router.use("/chat", chatRoutes);
router.use("/teachers", teacherRoutes);
router.use("/quiz", quizRoutes);
router.use("/subjects", subjectRoutes);
router.use("/roadmap", roadmapRoutes);
router.use("/escape", escapeRoutes);
router.use("/dungeon", dungeonRoutes);
router.use("/leaderboard", leaderboardRoutes);
export default router;
